export const LangStrings = {
  ca: {
    projecte: "Projecte",
    territori: "Territori",
    sostenibilitat: "Sostenibilitat",
    quisom: "Qui Som",
    ruta: "Ruta",
    material: "Material",
    passaport: "Passaport",
    passaporticaus: "Passaport i Caus",
    caus: "Els Caus de la Fera",
    marxandatge: "Marxandatge",
    agencia: "Agència",
    acces: "Accés",
    fera500: "Fera 500",
    fera300: "Fera 300",
    fera200: "Fera 200",
    fera150: "Fera 150",
  },
  es: {
    projecte: "Proyecto",
    territori: "Territorio",
    sostenibilitat: "Sostenibilidad",
    quisom: "Quienes Somos",
    ruta: "Ruta",
    material: "Material",
    passaport: "Passaporte",
    passaporticaus: "Pasaporte y Madrigueras",
    caus: "Las Madrigueras de la Fera",
    marxandatge: "Merchandising",
    agencia: "Agencia",
    acces: "Acceso",
  },
  en: {
    projecte: "Project",
    territori: "Territory",
    sostenibilitat: "Sustainability",
    quisom: "Who are we",
    ruta: "Route",
    material: "Material",
    passaport: "Passport",
    passaporticaus: "Passport and Dens",
    caus: "Fera's Dens",
    marxandatge: "Merchandising",
    agencia: "Agency",
    acces: "Access",
  }
}
