import Head from 'next/head'
import Logo from '@/src/components/Logo/Logo'
import BackgroundImage from '@/src/components/BackgroundImage/BackgroundImage'
import Footer from '@/src/components/Footer/Footer'

import styles from '@/src/styles/Home.module.css'
import backgroundImage from '@/public/img/fons_document_fera-04.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>FERA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundImage image={backgroundImage} />

      <div className={styles.main}>
        <div style={{width: 300, height: 300}}>
          <Logo />
        </div>
      </div>

      <Footer />
    </>
  )
}
