import Head from 'next/head'
import Image from 'next/image'
import Logo from '@components/Logo/Logo'
import Footer from '@components/Footer/Footer'
import backgroundImage from '@public/img/portada2.jpg'

import styles from '@styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>FERA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.background_image}>
        <Image src={backgroundImage} alt="" fill style={{objectFit:"cover"}} />
      </div>

      <div className={styles.main}>
        <div className={styles.logo}>
          <Logo />
        </div>
        <Footer />
      </div>
    </>
  )
}
